### ISSUE TITLE
Crash compile when OFF_PEAK_TARIFF is defined

### ISSUE THREAD

**Issue by Olorin113** [FredM67/PVRouter-3-phase#7]
**Describe the bug**
Quand OFF_PEAK_TARIFF est défini, le programme ne compile plus

**To Reproduce**
1. Décommenter la ligne  : #define OFF_PEAK_TARIFF

**Expected behavior**
La Compilation doit s'effectuer 

**logs**

```
`mk2_pvrouter_3phases.ino: In constructor '_rg_OffsetForce<N>::_rg_OffsetForce()':
mk2_pvrouter_3phases.ino:428:3: error: constexpr constructor does not have empty body
   }
   ^
mk2_pvrouter_3phases.ino: At global scope:
mk2_pvrouter_3phases.ino:437:66: error: the type 'const _rg_OffsetForce<2>' of constexpr variable 'rg_OffsetForce' is not literal
 constexpr auto rg_OffsetForce = _rg_OffsetForce<NO_OF_DUMPLOADS>(); /**< start & stop offsets for each load */
                                                                  ^
mk2_pvrouter_3phases/mk2_pvrouter_3phases.ino:404:7: note: '_rg_OffsetForce<2>' is not literal because:
 class _rg_OffsetForce
       ^~~~~~~~~~~~~~~
mk2_pvrouter_3phases/mk2_pvrouter_3phases.ino:404:7: note:   '_rg_OffsetForce<2>' is not an aggregate, does not have a trivial default constructor, and has no constexpr constructor that is not a copy or move constructor

exit status 1

Compilation error: constexpr constructor does not have empty body

```
`
**Development environment:**
 - ARDUINO IDE : Version: 2.0.2
Date: 2022-11-17T11:52:32.665Z
CLI Version: 0.29.0 [76251df9]

 - OS: Linux ubuntu 20.04

**Comment by FredM67** [comment]
Hi,
Ce n'est pas un bug. J'utilise certaines fonctionnalités purement C++17. Par défaut, l'Arduino IDE compile en C++11. Il faut changer ce paramètre dans le fichier platform.txt. Cf. Readme du sketch.
J'ai rajouté il y a quelques jours un static_assert pour vérifier si le compilateur est bien configuré.
Fred
